### ISSUE TITLE
Contentful module is it working correctly?

### ISSUE THREAD

**Issue by debs-obrien** [scaccogatto/contentful-module#6]
Hi, I recently did a live stream with the Contenful team and they tried out this module and couldn't get it to work. Has this module been updated lately and can we check on this to make sure it is correctly working as it should?

**Comment by scaccogatto** [comment]
It really works. I am using it in all my projects (production).
Tell me what happens and maybe I can help you.

**Comment by captainagile** [comment]
hello there, we couldn't get it to work too, nothing happens :(

Could you give us an example about the way you are retrieving contentful entries please?

**Comment by scaccogatto** [comment]
Everything is explained here: https://github.com/scaccogatto/contentful-module#usage

What is exactly not working? I am using this library in all my projects and everything is fine.
This is a real code I am using for a blog post page in an actual website:

`/pages/blog/_slug/index.vue`

```js
async asyncData({ app, params }) {
    const article = await app.$contentful.client
      .getEntries({
        content_type: 'blogPost',
        'fields.slug': params.slug,
        limit: 1,
        include: 10,
      })
      .then((q) => q.items[0])

    return { article }
  },
```

then `this.article` is available.

Did you configure Contentful correctly? You need an API key.
![image](https://user-images.githubusercontent.com/3670888/102334997-a2d9fb80-3f8f-11eb-8788-3df97e9c51c0.png)

Everything is explained here: https://github.com/scaccogatto/contentful-module#find-your-api-keys
What am I missing?
